# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'config'
    nugetConfigPath: '$(Build.SourcesDirectory)/Nuget/nuget.config'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/MdTranslator/MdTranslator.csproj'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)/src/MdTranslator/MdTranslator.csproj'
    arguments: '-o $(Build.BinariesDirectory)'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'felpasl pat'
    repositoryName: 'felpasl/MdTranslator'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: gitTag
    tag: $(Build.BuildNumber)      
    assets: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    changeLogCompareToRelease: 'lastFullRelease'
    changeLogType: 'commitBased'