orbs:
  github: haskell-works/github-release@1.0.0
version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Restore packages
          command:
            dotnet restore
      - run:
          name: Build App
          command:
            dotnet build
      - run: 
          name: Publish
          command:
            dotnet publish -c Release -o /build/out
  github/release:
          tag: v$CIRCLE_BUILD_NUM
          title: Release v$CIRCLE_BUILD_NUM
          filters:
            branches:
              only: master

